title: "Juan Meleiro"
name: "Juan Meleiro"
email: "juan.meleiro@me.com"
description: >- # this means to ignore newlines until "baseurl:"
    Meu site pessoal.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://juanmeleiro.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: "juanmeleiro"
github_username:  "juanmeleiro"
gitlab_username: "juanmeleiro"
disqus:
    shortname: juanmeleiro

# Build settings
plugins:
    # - jekyll-menus
    - jekyll-feed

      # permalink: /:year/:month/:day/:title
paginate: 10

header_pages:
    - about.md
    - cv.md
    - others.html

collections:
    turing:
        title: "Turing Archive"
        output: true
        relative_directory: 'others/turing'
    # mosaico:
    # mosatitle: "Textos da Mosaico"
    # mosaoutput: true
    # mosarelative_directory: 'others/mosaico'
